// automatically generated by the FlatBuffers compiler, do not modify

package wiki.models.item;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class CheckCacheRes extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static CheckCacheRes getRootAsCheckCacheRes(ByteBuffer _bb) { return getRootAsCheckCacheRes(_bb, new CheckCacheRes()); }
  public static CheckCacheRes getRootAsCheckCacheRes(ByteBuffer _bb, CheckCacheRes obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public CheckCacheRes __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public boolean cached() { int o = __offset(4); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createCheckCacheRes(FlatBufferBuilder builder,
      boolean cached) {
    builder.startTable(1);
    CheckCacheRes.addCached(builder, cached);
    return CheckCacheRes.endCheckCacheRes(builder);
  }

  public static void startCheckCacheRes(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addCached(FlatBufferBuilder builder, boolean cached) { builder.addBoolean(0, cached, false); }
  public static int endCheckCacheRes(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public CheckCacheRes get(int j) { return get(new CheckCacheRes(), j); }
    public CheckCacheRes get(CheckCacheRes obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

