// automatically generated by the FlatBuffers compiler, do not modify

package wiki.models.item;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class CheckCacheReq extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static CheckCacheReq getRootAsCheckCacheReq(ByteBuffer _bb) { return getRootAsCheckCacheReq(_bb, new CheckCacheReq()); }
  public static CheckCacheReq getRootAsCheckCacheReq(ByteBuffer _bb, CheckCacheReq obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public CheckCacheReq __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte hash(int j) { int o = __offset(4); return o != 0 ? bb.get(__vector(o) + j * 1) : 0; }
  public int hashLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public ByteVector hashVector() { return hashVector(new ByteVector()); }
  public ByteVector hashVector(ByteVector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer hashAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer hashInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }

  public static int createCheckCacheReq(FlatBufferBuilder builder,
      int hashOffset) {
    builder.startTable(1);
    CheckCacheReq.addHash(builder, hashOffset);
    return CheckCacheReq.endCheckCacheReq(builder);
  }

  public static void startCheckCacheReq(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addHash(FlatBufferBuilder builder, int hashOffset) { builder.addOffset(0, hashOffset, 0); }
  public static int createHashVector(FlatBufferBuilder builder, byte[] data) { return builder.createByteVector(data); }
  public static int createHashVector(FlatBufferBuilder builder, ByteBuffer data) { return builder.createByteVector(data); }
  public static void startHashVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static int endCheckCacheReq(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public CheckCacheReq get(int j) { return get(new CheckCacheReq(), j); }
    public CheckCacheReq get(CheckCacheReq obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

