// automatically generated by the FlatBuffers compiler, do not modify

package wiki.models.item;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ItemRes extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static ItemRes getRootAsItemRes(ByteBuffer _bb) { return getRootAsItemRes(_bb, new ItemRes()); }
  public static ItemRes getRootAsItemRes(ByteBuffer _bb, ItemRes obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ItemRes __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void startItemRes(FlatBufferBuilder builder) { builder.startTable(0); }
  public static int endItemRes(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ItemRes get(int j) { return get(new ItemRes(), j); }
    public ItemRes get(ItemRes obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

