// automatically generated by the FlatBuffers compiler, do not modify

package wiki.models.item;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Item extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static Item getRootAsItem(ByteBuffer _bb) { return getRootAsItem(_bb, new Item()); }
  public static Item getRootAsItem(ByteBuffer _bb, Item obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Item __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String name() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer nameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public double quality() { int o = __offset(6); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public wiki.models.item.Curiosity curiosity() { return curiosity(new wiki.models.item.Curiosity()); }
  public wiki.models.item.Curiosity curiosity(wiki.models.item.Curiosity obj) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public wiki.models.item.Food food() { return food(new wiki.models.item.Food()); }
  public wiki.models.item.Food food(wiki.models.item.Food obj) { int o = __offset(10); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createItem(FlatBufferBuilder builder,
      int nameOffset,
      double quality,
      int curiosityOffset,
      int foodOffset) {
    builder.startTable(4);
    Item.addQuality(builder, quality);
    Item.addFood(builder, foodOffset);
    Item.addCuriosity(builder, curiosityOffset);
    Item.addName(builder, nameOffset);
    return Item.endItem(builder);
  }

  public static void startItem(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(0, nameOffset, 0); }
  public static void addQuality(FlatBufferBuilder builder, double quality) { builder.addDouble(1, quality, 0.0); }
  public static void addCuriosity(FlatBufferBuilder builder, int curiosityOffset) { builder.addOffset(2, curiosityOffset, 0); }
  public static void addFood(FlatBufferBuilder builder, int foodOffset) { builder.addOffset(3, foodOffset, 0); }
  public static int endItem(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Item get(int j) { return get(new Item(), j); }
    public Item get(Item obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

