// automatically generated by the FlatBuffers compiler, do not modify

package wiki.models.item;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class SendRes extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static SendRes getRootAsSendRes(ByteBuffer _bb) { return getRootAsSendRes(_bb, new SendRes()); }
  public static SendRes getRootAsSendRes(ByteBuffer _bb, SendRes obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public SendRes __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void startSendRes(FlatBufferBuilder builder) { builder.startTable(0); }
  public static int endSendRes(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public SendRes get(int j) { return get(new SendRes(), j); }
    public SendRes get(SendRes obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

