// automatically generated by the FlatBuffers compiler, do not modify

package wiki.models.base;

public final class Type {
  private Type() { }
  public static final int ItemIsCached = 0;
  public static final int ItemSend = 1;

  public static final String[] names = { "ItemIsCached", "ItemSend", };

  public static String name(int e) { return names[e]; }
}

